CREATE TABLE IF NOT EXISTS asset_workstation_details (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL UNIQUE REFERENCES assets(id) ON DELETE CASCADE,
    monitoring_protocol VARCHAR(255),
    service_tag VARCHAR(255),
    last_logged_in_user VARCHAR(255),
    bios_date DATE,
    smbios_version VARCHAR(255),
    virtual_memory VARCHAR(255),
    virtual_memory_unit VARCHAR(50),
    logical_processors VARCHAR(255),
    bios_name VARCHAR(255),
    bios_version VARCHAR(255),
    bios_manufacturer VARCHAR(255),
    total_memory VARCHAR(255),
    total_memory_unit VARCHAR(50),
    domain VARCHAR(255),
    total_slots VARCHAR(255),
    operating_system VARCHAR(255),
    service_pack VARCHAR(255),
    build_number VARCHAR(255),
    license_type VARCHAR(255),
    system_drive VARCHAR(255),
    os_version VARCHAR(255),
    product_id VARCHAR(255),
    system_type VARCHAR(255),
    license_status VARCHAR(255),
    vm_platform VARCHAR(255),
    allowed_vms VARCHAR(255),
    installed_vms VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_asset_workstation_details_asset_id ON asset_workstation_details(asset_id);
